#!/usr/bin/env bash
# check-doctor.sh — the "doctor" family of harness coherence checks, split from
# the pre-v0.23.0 check-harness.sh monolith (block numbering retained for
# continuity). Standalone entry: scripts/harness/check-harness. The check-harness
# orchestrator runs every family and owns the combined summary.
set -uo pipefail
# shellcheck source=/dev/null
. "$(dirname "$0")/check-common.sh"

# 10. Doctor: conditions that silently weaken the harness. Warnings only —
#     they don't fail the build, they tell you where the floor is soft.
command -v jq >/dev/null 2>&1 \
    || echo "WARNING: jq not found — every guard hook fails open without it; the native permission deny lists are the only live layer"
if [ -f "$ROOT/AGENTS.md" ]; then
    agents_lines=$(wc -l < "$ROOT/AGENTS.md" | tr -d '[:space:]')
    [ "$agents_lines" -gt 120 ] \
        && echo "WARNING: AGENTS.md is $agents_lines lines (target <=120) — it should route to docs/, not explain; instruction compliance degrades as it grows"
fi
for skill in "$ROOT/$CANONICAL_SKILLS"/*/SKILL.md; do
    [ -f "$skill" ] || continue
    skill_rel=${skill#"$ROOT"/}
    skill_lines=$(wc -l < "$skill" | tr -d '[:space:]')
    [ "$skill_lines" -gt 500 ] \
        && echo "WARNING: $skill_rel is $skill_lines lines (target <=500) — move detail into the skill's references/ (progressive disclosure)"
done
# (Skill name/description spec conformance — kebab-case, length, non-empty,
#  name==dir — is now enforced as ERRORs in check 1, not warned here.)


# 10d. Doctor: CI workflow actions should be pinned to an immutable commit SHA.
#      A `uses:` ref pointing at a tag or branch is mutable — a retagged or
#      compromised third-party action would run with the workflow's token, the
#      supply-chain exposure the shipped-CI hardening closes. Local `uses: ./path`
#      composite actions are first-party and skipped, as are `docker://` refs
#      (a different pinning model). Freshness/hygiene WARNING like the other
#      doctor checks — it never fails the build. Best-effort line scan; full
#      YAML parsing is out of scope.
if [ -d "$ROOT/.github/workflows" ]; then
    for wf in "$ROOT"/.github/workflows/*.yml "$ROOT"/.github/workflows/*.yaml; do
        [ -f "$wf" ] || continue
        wf_rel=${wf#"$ROOT"/}
        while IFS= read -r ref; do
            [ -n "$ref" ] || continue
            case "$ref" in
                ./*|docker://*) continue ;;
            esac
            # ${ref##*@} is the pin (the whole ref when there is no '@' — an
            # unpinned owner/repo is mutable too). A full commit SHA is 40 hex.
            if ! printf '%s' "${ref##*@}" | grep -qE '^[0-9a-fA-F]{40}$'; then
                echo "WARNING: $wf_rel uses '$ref' pinned to a mutable ref — pin third-party actions to a full 40-char commit SHA (a tag or branch can be moved under you); keep the human-readable tag in a trailing comment"
            fi
        done < <(grep -oE '^[[:space:]]*-?[[:space:]]*uses:[[:space:]]*[^[:space:]]+' "$wf" 2>/dev/null \
                    | sed -E 's/^[[:space:]]*-?[[:space:]]*uses:[[:space:]]*//' \
                    | tr -d "\"'")
    done
fi


# 10e. Doctor: a repo-wide code formatter must exclude the harness's
#      checksum-pinned and generated-but-unpinned paths. A formatter rewrite
#      of a pinned file trips check-drift's checksum verification (an ERROR);
#      a rewrite of a generated-but-unpinned stub (provider skill/agent stub
#      dirs, .harness/adapters/ — regenerated by `sync`, so never in
#      scripts/harness/.harness-manifest) desyncs it from its generator with
#      nothing to catch it. WARNING only, like every doctor check: "a
#      repo-wide formatter is configured" is a coarse presence signal (a
#      config file existing), not proof the tool's file types actually
#      overlap kit-owned paths, so a false positive here must never block a
#      build. The exclusion mechanism is NOT interchangeable across tools —
#      pointing a biome user at .prettierignore is actively wrong — so every
#      branch below names only its own tool's mechanism. Best-effort
#      line/text scanning, exactly like 10d; full config parsing (real YAML,
#      biome's ordered-negation evaluation) is out of scope. jq is required
#      to read biome/dprint's JSON; its absence, or a config jq can't parse
#      (JSONC comments are not valid JSON), degrades to a hedged warning that
#      says so — it never claims a path is excluded without having actually
#      parsed the config that would prove it.

# _10e_covers <entries, newline-separated> <path> — best-effort: does some
# entry, after stripping quoting/glob noise, equal <path> or name a directory
# <path> sits under? Not a real glob engine; a mid-pattern wildcard (e.g.
# "scripts/**/*.sh") degrades to a broad match via case's own pattern
# matching, which trends toward more false "covered" verdicts, not fewer —
# the safer direction for a check that only ever WARNs. Both "./foo" and
# gitignore-style anchored "/foo" strip down to the same "foo" — an anchored
# entry is idiomatic and correct in a .prettierignore/.pre-commit exclude and
# must not false-positive just because it starts with "/".
_10e_covers() {
    local _entries="$1" _path="$2" _e
    while IFS= read -r _e; do
        [ -n "$_e" ] || continue
        _e=${_e#\!}
        _e=${_e#./}
        _e=${_e#/}
        _e=$(printf '%s' "$_e" | tr -d "\"'")
        _e=${_e%/\*\*}
        _e=${_e%/\*}
        _e=${_e%\*}
        _e=${_e%/}
        [ -n "$_e" ] || continue
        # $_e is deliberately UNQUOTED here: a stripped catch-all entry
        # ("**" -> "*") must still glob-match as a wildcard, not the literal
        # character "*" — that is the whole point of stripping the glob
        # noise above. Quoting it (shellcheck's usual SC2254 advice) would
        # make a repo-wide "**" include silently never reach any path.
        # shellcheck disable=SC2254
        case "$_path" in
            $_e|$_e/*) return 0 ;;
        esac
    done <<EOF
$_entries
EOF
    return 1
}

# _10e_formatter_parseable <path> — true if <path>'s extension is one a
# repo-wide formatter (prettier/biome/dprint/a pre-commit formatter hook)
# could plausibly rewrite. A real adopter's .harness-manifest is mostly
# scripts/harness/**/*.sh entries (shell has no formatter in this set that
# parses it at all) plus a couple of non-code files
# (e.g. .harness/gates.conf); passing
# every entry through verbatim turned the manifest-derived half of this check
# into permanent, unfixable noise — .sh paths no .prettierignore/.pre-commit
# exclude could ever cover with a formatter that doesn't touch shell.
_10e_formatter_parseable() {
    case "$1" in
        *.md|*.json|*.jsonc|*.yml|*.yaml|*.css|*.js|*.jsx|*.ts|*.tsx|*.html) return 0 ;;
        *) return 1 ;;
    esac
}

# Kit-owned path set: manifest-pinned paths collapsed to the two roots
# nearly everything funnels through (scripts/harness/, .harness/), plus the
# surface the manifest can't see because it is regenerated, not
# integrity-pinned (adapters + per-provider stub dirs, derived from the same
# PROVIDERS/AGENT_PROVIDERS check-common.sh already resolved). Only
# manifest entries a formatter could actually parse feed the collapse below —
# see _10e_formatter_parseable. This also closes a real gap: harness_append_
# formatterignore's own written block (install-lib.sh) lists ".harness/
# adapters/" but never a bare ".harness/" entry, so if EVERY .harness/*
# manifest pin were let through (gates.conf, hooks/guard-project-policy.sh —
# both formatter-unparseable), the collapsed ".harness" kit path would be
# something the kit's own remedy can never satisfy, and this check would WARN
# on it forever. Filtering first means ".harness" only appears as a kit path
# when a manifest pin actually justifies it.
_10e_kit_paths=""
_10e_add_kit_path() {
    case $'\n'"$_10e_kit_paths"$'\n' in
        *$'\n'"$1"$'\n'*) ;;
        *) _10e_kit_paths="$_10e_kit_paths
$1" ;;
    esac
}
if [ -f "$MANIFEST" ]; then
    while IFS= read -r _10e_p; do
        [ -n "$_10e_p" ] || continue
        _10e_formatter_parseable "$_10e_p" || continue
        case "$_10e_p" in
            scripts/harness/*) _10e_add_kit_path "scripts/harness" ;;
            .harness/*) _10e_add_kit_path ".harness" ;;
            *) _10e_add_kit_path "$_10e_p" ;;
        esac
    done <<EOF
$(awk '$1 ~ /^[0-9a-fA-F]{64}$/ {print $2}' "$MANIFEST" 2>/dev/null)
EOF
fi
_10e_add_kit_path ".harness/adapters"
for _10e_prov in $PROVIDERS; do
    _10e_add_kit_path "$_10e_prov/skills"
done
for _10e_prov in ${AGENT_PROVIDERS:-}; do
    _10e_add_kit_path "$_10e_prov/agents"
done
_10e_kit_paths=$(printf '%s\n' "$_10e_kit_paths" | sed '/^$/d')
_10e_kit_list=$(printf '%s' "$_10e_kit_paths" | tr '\n' ' ')

# -- prettier: .prettierignore is the exclusion mechanism (plain text, one
#    glob per line, '#' comments; no jq needed) --
# Trigger broadened beyond "a prettier config file exists": prettier runs
# perfectly well with zero config (e.g. a bare `prettier --write .` package.json
# script), which is exactly the adopter-reported case that motivated this fix —
# a config-file-only trigger silently never warned them. Fire on any of:
# a config file, "prettier" appearing anywhere in package.json (dependency,
# devDependency, or a script string — a plain grep, deliberately not a
# tokenizer), or a .prettierignore that already exists (it exists for a
# reason, and its coverage is worth checking regardless of how we found it).
_10e_prettier=0
for _10e_f in .prettierrc .prettierrc.json .prettierrc.yml .prettierrc.yaml \
              .prettierrc.json5 .prettierrc.js .prettierrc.cjs .prettierrc.mjs \
              .prettierrc.toml prettier.config.js prettier.config.cjs prettier.config.mjs; do
    [ -f "$ROOT/$_10e_f" ] && _10e_prettier=1
done
if [ -f "$ROOT/package.json" ] && grep -qE '"prettier' "$ROOT/package.json" 2>/dev/null; then
    _10e_prettier=1
fi
[ -f "$ROOT/.prettierignore" ] && _10e_prettier=1
if [ "$_10e_prettier" = "1" ]; then
    if [ ! -f "$ROOT/.prettierignore" ]; then
        echo "WARNING: prettier is configured but .prettierignore does not exist — add the harness's kit-owned paths ($_10e_kit_list) to .prettierignore, or prettier will rewrite checksum-pinned/generated files and check-harness's drift check will hard-fail"
    else
        # Includes and negations evaluated SEPARATELY, like the biome branch
        # below: a path is covered only if some entry ignores it AND no '!'
        # entry re-includes it. _10e_covers alone strips a leading '!'
        # unconditionally, so passing raw entries straight through (the prior
        # bug) let a re-including negation (e.g. "scripts/harness/" followed
        # by "!scripts/harness/") read as coverage — the single most dangerous
        # config this check can meet, and it stayed silent.
        _10e_entries=$(grep -vE '^[[:space:]]*(#|$)' "$ROOT/.prettierignore" 2>/dev/null)
        _10e_neg=$(printf '%s\n' "$_10e_entries" | grep '^!')
        _10e_inc=$(printf '%s\n' "$_10e_entries" | grep -v '^!')
        _10e_missing=""
        while IFS= read -r _10e_kp; do
            [ -n "$_10e_kp" ] || continue
            if _10e_covers "$_10e_inc" "$_10e_kp" && ! _10e_covers "$_10e_neg" "$_10e_kp"; then
                :
            else
                _10e_missing="$_10e_missing $_10e_kp"
            fi
        done <<EOF
$_10e_kit_paths
EOF
        [ -n "$_10e_missing" ] \
            && echo "WARNING: .prettierignore does not cover kit-owned path(s):$_10e_missing — prettier will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail; add them to .prettierignore"
    fi
fi

# _10e_biome_included <entries, newline-separated, ORDER PRESERVED> <path> —
# biome's own documented semantics: includes/excludes are evaluated in
# order and the LAST entry matching <path> decides whether it's included,
# not "was there ever a matching negation anywhere in the list" (that
# unordered approximation is what _10e_covers's callers use for prettier/
# dprint/pre-commit, where the underlying tool has no negation ordering to
# get wrong — biome is the one format this check models with real ordering,
# and getting it wrong here is what let `["!scripts/harness/**", "**"]`
# — negation FOLLOWED by a later catch-all include that overrides it — read
# as excluded when biome would actually reformat every kit path). Returns 0
# (included -> formatter WILL touch <path>) or 1 (excluded). Starts at
# "excluded": <entries> is never truly empty by the time this is called (the
# caller substitutes a literal "**" for biome's own empty-includes-means-
# everything default), so a real, non-catch-all includes list that simply
# never mentions <path> (e.g. a repo scoped to "src/**" only) must default to
# NOT reached, not the other way around.
_10e_biome_included() {
    local _entries="$1" _path="$2" _e _neg _included=0
    while IFS= read -r _e; do
        [ -n "$_e" ] || continue
        case "$_e" in
            '!'*) _neg=1 ;;
            *) _neg=0 ;;
        esac
        _e=${_e#\!}
        _e=${_e#./}
        _e=${_e#/}
        _e=$(printf '%s' "$_e" | tr -d "\"'")
        _e=${_e%/\*\*}
        _e=${_e%/\*}
        _e=${_e%\*}
        _e=${_e%/}
        [ -n "$_e" ] || continue
        # shellcheck disable=SC2254
        case "$_path" in
            $_e|$_e/*) [ "$_neg" = "1" ] && _included=0 || _included=1 ;;
        esac
    done <<EOF
$_entries
EOF
    [ "$_included" = "1" ]
}

# -- biome: files.includes / formatter.includes with ordered '!' negations --
_10e_biome_cfg=""
[ -f "$ROOT/biome.json" ] && _10e_biome_cfg="$ROOT/biome.json"
[ -f "$ROOT/biome.jsonc" ] && _10e_biome_cfg="$ROOT/biome.jsonc"
if [ -n "$_10e_biome_cfg" ]; then
    _10e_rel=${_10e_biome_cfg#"$ROOT"/}
    if ! command -v jq >/dev/null 2>&1; then
        echo "WARNING: $_10e_rel found but jq is not available — cannot verify whether kit-owned paths ($_10e_kit_list) are excluded via an ordered '!' negation in files.includes/formatter.includes; check manually"
    else
        _10e_json=$(jq -c '.' "$_10e_biome_cfg" 2>/dev/null)
        if [ -z "$_10e_json" ]; then
            echo "WARNING: $_10e_rel could not be parsed as JSON (JSONC comments/trailing commas are not valid JSON) — cannot verify kit-owned paths ($_10e_kit_list) are excluded from biome formatting; check files.includes/formatter.includes manually"
        else
            _10e_enabled=$(printf '%s' "$_10e_json" | jq -r 'if .formatter.enabled == false then "false" else "true" end' 2>/dev/null)
            if [ "$_10e_enabled" = "true" ]; then
                _10e_all=$(printf '%s' "$_10e_json" | jq -r '(.formatter.includes // .files.includes // []) | .[]?' 2>/dev/null)
                [ -z "$_10e_all" ] && _10e_all='**'
                _10e_missing=""
                while IFS= read -r _10e_kp; do
                    [ -n "$_10e_kp" ] || continue
                    _10e_biome_included "$_10e_all" "$_10e_kp" && _10e_missing="$_10e_missing $_10e_kp"
                done <<EOF
$_10e_kit_paths
EOF
                [ -n "$_10e_missing" ] \
                    && echo "WARNING: $_10e_rel's files.includes/formatter.includes reaches kit-owned path(s):$_10e_missing without an ordered '!' negation excluding them — add e.g. \"!scripts/harness/**\" after the including entry, or biome will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail"
            fi
        fi
    fi
fi

# -- dprint: top-level "excludes" (a plain list, no negation ordering) --
_10e_dprint_cfg=""
[ -f "$ROOT/dprint.json" ] && _10e_dprint_cfg="$ROOT/dprint.json"
[ -f "$ROOT/dprint.jsonc" ] && _10e_dprint_cfg="$ROOT/dprint.jsonc"
if [ -n "$_10e_dprint_cfg" ]; then
    _10e_rel=${_10e_dprint_cfg#"$ROOT"/}
    if ! command -v jq >/dev/null 2>&1; then
        echo "WARNING: $_10e_rel found but jq is not available — cannot verify whether kit-owned paths ($_10e_kit_list) are listed in its \"excludes\"; check manually"
    else
        _10e_json=$(jq -c '.' "$_10e_dprint_cfg" 2>/dev/null)
        if [ -z "$_10e_json" ]; then
            echo "WARNING: $_10e_rel could not be parsed as JSON (JSONC comments/trailing commas are not valid JSON) — cannot verify kit-owned paths ($_10e_kit_list) are listed in its \"excludes\"; check manually"
        else
            _10e_inc=$(printf '%s' "$_10e_json" | jq -r '.includes // [] | .[]?' 2>/dev/null)
            _10e_exc=$(printf '%s' "$_10e_json" | jq -r '.excludes // [] | .[]?' 2>/dev/null)
            [ -z "$_10e_inc" ] && _10e_inc='**'
            _10e_missing=""
            while IFS= read -r _10e_kp; do
                [ -n "$_10e_kp" ] || continue
                if _10e_covers "$_10e_inc" "$_10e_kp"; then
                    _10e_covers "$_10e_exc" "$_10e_kp" || _10e_missing="$_10e_missing $_10e_kp"
                fi
            done <<EOF
$_10e_kit_paths
EOF
            [ -n "$_10e_missing" ] \
                && echo "WARNING: $_10e_rel's \"includes\" reaches kit-owned path(s):$_10e_missing not listed in its \"excludes\" — add them to \"excludes\", or dprint will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail"
        fi
    fi
fi

# _10e_pc_hook_unscoped <cfg-file> — prints "1" if some pre-commit hook
# matching a known formatter name lacks its OWN 'files:' restriction (i.e.
# would run over the whole tree), else "0". Best-effort block scan, not a
# real YAML/indentation parser: a hook item starts at a '- id:' line; a
# '- repo:' line carries the formatter-name signal forward (a repo's own
# hooks can share a generic 'id:' with no formatter keyword in it) but is
# never itself checked for 'files:' (that field lives on the id: entry in
# real pre-commit YAML, never directly on repo:). This exists so an
# UNRELATED hook's 'files:' a few lines away in the same file can no longer
# be misattributed to a different, actually-unscoped formatter hook — the
# prior version's whole-file "does 'files:' appear anywhere" grep conflated
# the two, which is exactly as unsafe as the substring bug below.
_10e_pc_hook_unscoped() {
    awk '
        BEGIN { repo_fmt = 0; in_id = 0; is_fmt = 0; has_files = 0; unscoped = 0 }
        /^[[:space:]]*-[[:space:]]*repo:/ {
            if (in_id && is_fmt && !has_files) unscoped = 1
            in_id = 0; is_fmt = 0; has_files = 0; repo_fmt = 0
            if ($0 ~ /(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)/) repo_fmt = 1
            next
        }
        /^[[:space:]]*-[[:space:]]*id:/ {
            if (in_id && is_fmt && !has_files) unscoped = 1
            in_id = 1; is_fmt = repo_fmt; has_files = 0
            if ($0 ~ /(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)/) is_fmt = 1
            next
        }
        in_id && /^[[:space:]]*files:/ { has_files = 1 }
        END { if (in_id && is_fmt && !has_files) unscoped = 1; print unscoped }
    ' "$1" 2>/dev/null
}

# -- pre-commit: a top-level 'exclude:' regex, checked per kit path (fix:
#    coverage is no longer inferred from the word "harness" merely appearing
#    somewhere in the pattern — that let an exclude naming only two of five
#    required paths silently clear all five), or the formatter hook's OWN
#    'files:' (fix: now block-attributed via _10e_pc_hook_unscoped instead of
#    "does any 'files:' appear anywhere in the file"). No YAML parser
#    dependency (best-effort text scan only, like the rest of this check).
#    Per the warning-only principle: when per-path coverage genuinely can't
#    be proven (no YAML parser here), this WARNs with hedged wording instead
#    of silently assuming it. --
_10e_pc_cfg=""
[ -f "$ROOT/.pre-commit-config.yaml" ] && _10e_pc_cfg="$ROOT/.pre-commit-config.yaml"
[ -f "$ROOT/.pre-commit-config.yml" ] && _10e_pc_cfg="$ROOT/.pre-commit-config.yml"
if [ -n "$_10e_pc_cfg" ]; then
    _10e_rel=${_10e_pc_cfg#"$ROOT"/}
    if grep -qE '(repo:|id:)[[:space:]]*.*(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)' "$_10e_pc_cfg" 2>/dev/null; then
        if [ "$(_10e_pc_hook_unscoped "$_10e_pc_cfg")" = "1" ]; then
            _10e_global_exclude=$(grep -E '^exclude:' "$_10e_pc_cfg" 2>/dev/null | head -n1)
            _10e_missing=""
            while IFS= read -r _10e_kp; do
                [ -n "$_10e_kp" ] || continue
                case "$_10e_global_exclude" in
                    *"$_10e_kp"*) ;;
                    *) _10e_missing="$_10e_missing $_10e_kp" ;;
                esac
            done <<EOF
$_10e_kit_paths
EOF
            [ -n "$_10e_missing" ] \
                && echo "WARNING: $_10e_rel runs a formatter hook not scoped by its own 'files:' — no real YAML parser here, so coverage can only be checked against a top-level 'exclude:', which does not demonstrably cover kit-owned path(s):$_10e_missing — pre-commit will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail unless they are actually excluded"
        fi
    fi
fi


check_trailer "doctor"
