#!/usr/bin/env bash
# check-doctor.sh — the "doctor" family of harness coherence checks, split from
# the pre-v0.23.0 check-harness.sh monolith (block numbering retained for
# continuity). Standalone entry: scripts/harness/check-harness. The check-harness
# orchestrator runs every family and owns the combined summary.
set -uo pipefail
# shellcheck source=/dev/null
. "$(dirname "$0")/check-common.sh"

# 10. Doctor: conditions that silently weaken the harness. Warnings only —
#     they don't fail the build, they tell you where the floor is soft.
command -v jq >/dev/null 2>&1 \
    || echo "WARNING: jq not found — every guard hook fails open without it; the native permission deny lists are the only live layer"
if [ -f "$ROOT/AGENTS.md" ]; then
    agents_lines=$(wc -l < "$ROOT/AGENTS.md" | tr -d '[:space:]')
    [ "$agents_lines" -gt 120 ] \
        && echo "WARNING: AGENTS.md is $agents_lines lines (target <=120) — it should route to docs/, not explain; instruction compliance degrades as it grows"
fi
for skill in "$ROOT/$CANONICAL_SKILLS"/*/SKILL.md; do
    [ -f "$skill" ] || continue
    skill_rel=${skill#"$ROOT"/}
    skill_lines=$(wc -l < "$skill" | tr -d '[:space:]')
    [ "$skill_lines" -gt 500 ] \
        && echo "WARNING: $skill_rel is $skill_lines lines (target <=500) — move detail into the skill's references/ (progressive disclosure)"
done
# (Skill name/description spec conformance — kebab-case, length, non-empty,
#  name==dir — is now enforced as ERRORs in check 1, not warned here.)


# 10d. Doctor: CI workflow actions should be pinned to an immutable commit SHA.
#      A `uses:` ref pointing at a tag or branch is mutable — a retagged or
#      compromised third-party action would run with the workflow's token, the
#      supply-chain exposure the shipped-CI hardening closes. Local `uses: ./path`
#      composite actions are first-party and skipped, as are `docker://` refs
#      (a different pinning model). Freshness/hygiene WARNING like the other
#      doctor checks — it never fails the build. Best-effort line scan; full
#      YAML parsing is out of scope.
if [ -d "$ROOT/.github/workflows" ]; then
    for wf in "$ROOT"/.github/workflows/*.yml "$ROOT"/.github/workflows/*.yaml; do
        [ -f "$wf" ] || continue
        wf_rel=${wf#"$ROOT"/}
        while IFS= read -r ref; do
            [ -n "$ref" ] || continue
            case "$ref" in
                ./*|docker://*) continue ;;
            esac
            # ${ref##*@} is the pin (the whole ref when there is no '@' — an
            # unpinned owner/repo is mutable too). A full commit SHA is 40 hex.
            if ! printf '%s' "${ref##*@}" | grep -qE '^[0-9a-fA-F]{40}$'; then
                echo "WARNING: $wf_rel uses '$ref' pinned to a mutable ref — pin third-party actions to a full 40-char commit SHA (a tag or branch can be moved under you); keep the human-readable tag in a trailing comment"
            fi
        done < <(grep -oE '^[[:space:]]*-?[[:space:]]*uses:[[:space:]]*[^[:space:]]+' "$wf" 2>/dev/null \
                    | sed -E 's/^[[:space:]]*-?[[:space:]]*uses:[[:space:]]*//' \
                    | tr -d "\"'")
    done
fi


# 10e. Doctor: a repo-wide code formatter must exclude the harness's
#      checksum-pinned and generated-but-unpinned paths. A formatter rewrite
#      of a pinned file trips check-drift's checksum verification (an ERROR);
#      a rewrite of a generated-but-unpinned stub (provider skill/agent stub
#      dirs, .harness/adapters/ — regenerated by `sync`, so never in
#      scripts/harness/.harness-manifest) desyncs it from its generator with
#      nothing to catch it. WARNING only, like every doctor check: "a
#      repo-wide formatter is configured" is a coarse presence signal (a
#      config file existing), not proof the tool's file types actually
#      overlap kit-owned paths, so a false positive here must never block a
#      build. The exclusion mechanism is NOT interchangeable across tools —
#      pointing a biome user at .prettierignore is actively wrong — so every
#      branch below names only its own tool's mechanism. Best-effort
#      line/text scanning, exactly like 10d; full config parsing (real YAML,
#      biome's ordered-negation evaluation) is out of scope. jq is required
#      to read biome/dprint's JSON; its absence, or a config jq can't parse
#      (JSONC comments are not valid JSON), degrades to a hedged warning that
#      says so — it never claims a path is excluded without having actually
#      parsed the config that would prove it.

# _10e_covers <entries, newline-separated> <path> — best-effort: does some
# entry, after stripping quoting/glob noise, equal <path> or name a directory
# <path> sits under? Not a real glob engine; a mid-pattern wildcard (e.g.
# "scripts/**/*.sh") degrades to a broad match via case's own pattern
# matching, which trends toward more false "covered" verdicts, not fewer —
# the safer direction for a check that only ever WARNs. Both "./foo" and
# gitignore-style anchored "/foo" strip down to the same "foo" — an anchored
# entry is idiomatic and correct in a .prettierignore/.pre-commit exclude and
# must not false-positive just because it starts with "/". A leading "**/" is
# stripped for the same reason and is the OPPOSITE case: "**/foo" matches foo
# at any depth INCLUDING the root, so it covers the root kit path this check
# asks about — and it is the form the kit's own written block now uses (see
# harness_append_formatterignore), so failing to strip it would make the kit
# warn about a remedy it just applied.
#
# That prefix strip is narrow on BOTH sides, because the obvious wide version
# breaks two shapes that used to work:
#   - it fires only when a real path component follows ("**/" then at least
#     one character that is neither "*" nor "/"). A CATCH-ALL spelled "**/*"
#     would otherwise strip to "*" and then be reduced to the empty string by
#     the trailing-glob strips below and skipped entirely — turning the
#     single most permissive include a config can carry into "reaches
#     nothing", which is how a repo-wide biome `includes: ["**/*"]` would
#     stop warning altogether. Bare "**/" and "**/**" fall through here for
#     the same reason and reach the catch-all handling below;
#   - a stripped entry keeps its DEPTH match via the "*/" alternatives in the
#     case below. "**/adapters/" means "adapters at any depth" and must still
#     read as covering ".harness/adapters"; before the strip existed it did,
#     accidentally, because "**" survived into the pattern as "*". Dropping
#     that would move coverage rather than widen it — and in the biome
#     direction (see _10e_biome_included, same shape) an entry that stops
#     matching reads as "not reached", i.e. silence where the formatter
#     really would rewrite the path.
_10e_covers() {
    local _entries="$1" _path="$2" _e _dd
    while IFS= read -r _e; do
        [ -n "$_e" ] || continue
        _e=${_e#\!}
        _e=${_e#./}
        _e=${_e#/}
        _e=$(printf '%s' "$_e" | tr -d "\"'")
        _dd=0
        while :; do
            case "$_e" in
                '**/'*[!*/]*) _dd=1; _e=${_e#\*\*/} ;;
                *) break ;;
            esac
        done
        _e=${_e%/\*\*}
        _e=${_e%/\*}
        _e=${_e%\*}
        _e=${_e%/}
        [ -n "$_e" ] || continue
        # $_e is deliberately UNQUOTED here: a stripped catch-all entry
        # ("**" -> "*") must still glob-match as a wildcard, not the literal
        # character "*" — that is the whole point of stripping the glob
        # noise above. Quoting it (shellcheck's usual SC2254 advice) would
        # make a repo-wide "**" include silently never reach any path.
        if [ "$_dd" = "1" ]; then
            # shellcheck disable=SC2254
            case "$_path" in
                $_e|$_e/*|*/$_e|*/$_e/*) return 0 ;;
            esac
        else
            # shellcheck disable=SC2254
            case "$_path" in
                $_e|$_e/*) return 0 ;;
            esac
        fi
    # DELIBERATELY still a here-doc (see assert_loop_ran in check-common.sh):
    # this loop returns on the first covering entry, and process substitution
    # would leave the `printf` writer taking an EPIPE under an inherited-ignored
    # SIGPIPE. Losing this loop fails CLOSED — "not covered", which its callers
    # turn into a WARNING — so it cannot produce the silent pass the converted
    # loops below could.
    done <<EOF
$_entries
EOF
    return 1
}

# _10e_formatter_parseable <path> — true if <path>'s extension is one a
# repo-wide formatter (prettier/biome/dprint/a pre-commit formatter hook)
# could plausibly rewrite. A real adopter's .harness-manifest is mostly
# scripts/harness/**/*.sh entries (shell has no formatter in this set that
# parses it at all) plus a couple of non-code files
# (e.g. .harness/gates.conf); passing
# every entry through verbatim turned the manifest-derived half of this check
# into permanent, unfixable noise — .sh paths no .prettierignore/.pre-commit
# exclude could ever cover with a formatter that doesn't touch shell.
_10e_formatter_parseable() {
    case "$1" in
        *.md|*.json|*.jsonc|*.yml|*.yaml|*.css|*.js|*.jsx|*.ts|*.tsx|*.html) return 0 ;;
        *) return 1 ;;
    esac
}

# Kit-owned path set: manifest-pinned paths collapsed to the two roots
# nearly everything funnels through (scripts/harness/, .harness/), plus the
# surface the manifest can't see because it is regenerated, not
# integrity-pinned (adapters + per-provider stub dirs, derived from the same
# PROVIDERS/AGENT_PROVIDERS check-common.sh already resolved). Only
# manifest entries a formatter could actually parse feed the collapse below —
# see _10e_formatter_parseable. This also closes a real gap: harness_append_
# formatterignore's own written block (install-lib.sh) lists ".harness/
# adapters/" but never a bare ".harness/" entry, so if EVERY .harness/*
# manifest pin were let through (gates.conf, hooks/guard-project-policy.sh —
# both formatter-unparseable), the collapsed ".harness" kit path would be
# something the kit's own remedy can never satisfy, and this check would WARN
# on it forever. Filtering first means ".harness" only appears as a kit path
# when a manifest pin actually justifies it.
_10e_kit_paths=""
_10e_add_kit_path() {
    case $'\n'"$_10e_kit_paths"$'\n' in
        *$'\n'"$1"$'\n'*) ;;
        *) _10e_kit_paths="$_10e_kit_paths
$1" ;;
    esac
}

# Representative DESCENDANT files (one flat newline list). The collapse to
# bare directories above is only safe for prefix-style IGNORE matching
# ("scripts/harness/" covers everything under it, and a missed match there
# fails toward a warning — noise, this check's accepted direction). On an
# INCLUDE side it inverts (issue #16): an extension-style include like
# "**/*.md" can never string-match the bare directory "scripts/harness", so
# every kit path read as "not reached" and the check stayed SILENT while the
# formatter really would rewrite the pinned/generated .md files — the exact
# failure direction _10e_biome_included's own header calls the dangerous one.
# So include-side matching asks a second question (see _10e_reached below):
# does the include reach the directory (kept — a dir-shaped include must
# still count) OR any representative descendant file under it? Pinned
# formatter-parseable paths are their own representatives, captured here
# before the collapse discards them; the generated dirs the manifest cannot
# see get a synthesized stand-in, so the answer stays sensible in a repo
# whose stubs are not yet generated on disk (adapters and stub files are .md
# — codex agent stubs are TOML, approximated as .md here, which errs toward
# warning: noise again, the accepted side). The same list is what the
# pre-commit branch probes a hook-level regex against (issue #17): a
# 'files:' pattern anchors against the file paths pre-commit passes it, so
# testing it on bare directories has this same blind spot.
_10e_kit_reps=""
_10e_add_kit_rep() {
    case $'\n'"$_10e_kit_reps"$'\n' in
        *$'\n'"$1"$'\n'*) ;;
        *) _10e_kit_reps="$_10e_kit_reps
$1" ;;
    esac
}
if [ -f "$MANIFEST" ]; then
    # Every loop from here to the end of #10e reads through process
    # substitution and asserts it consumed its input — see assert_loop_ran in
    # check-common.sh. This one feeds the kit-path set the four formatter
    # branches below all compare against, so losing it does not merely drop one
    # warning: it silently narrows what every branch checks.
    _10e_pins=$(awk '$1 ~ /^[0-9a-fA-F]{64}$/ {print $2}' "$MANIFEST" 2>/dev/null)
    _10e_pins_read=0
    while IFS= read -r _10e_p; do
        _10e_pins_read=$((_10e_pins_read + 1))
        [ -n "$_10e_p" ] || continue
        _10e_formatter_parseable "$_10e_p" || continue
        _10e_add_kit_rep "$_10e_p"
        case "$_10e_p" in
            scripts/harness/*) _10e_add_kit_path "scripts/harness" ;;
            .harness/*) _10e_add_kit_path ".harness" ;;
            *) _10e_add_kit_path "$_10e_p" ;;
        esac
    done < <(printf '%s\n' "$_10e_pins")
    assert_loop_ran "$_10e_pins_read" "kit-owned path collection for formatter check #10e"
fi
_10e_add_kit_path ".harness/adapters"
_10e_add_kit_rep ".harness/adapters/x.md"
for _10e_prov in $PROVIDERS; do
    _10e_add_kit_path "$_10e_prov/skills"
    _10e_add_kit_rep "$_10e_prov/skills/x/SKILL.md"
done
for _10e_prov in ${AGENT_PROVIDERS:-}; do
    _10e_add_kit_path "$_10e_prov/agents"
    _10e_add_kit_rep "$_10e_prov/agents/x.md"
done

# A nested checkout of this repo holds a SECOND copy of every kit path above,
# and every exclusion mechanism in this check is path-anchored: a pattern with
# an interior slash ("scripts/harness/", "!scripts/harness/**", an
# '^scripts/harness/' regex) matches the root copy only. The reproduced case
# is Claude Code's worktree feature — .claude/worktrees/<name>/ is a full
# working copy kept out of Git via .git/info/exclude, which no formatter
# reads — so the formatter descends in, rewrites the pinned/generated files
# there, and the worktree's own check-drift hard-fails on an otherwise clean
# tree. Surfaced ONLY when the directory exists: a repo that has never made a
# worktree has nothing to exclude, and a WARN-only check must stay silent when
# it is not applicable. The hint rides along on every branch's warning below,
# because the fix differs per tool and none of them is prettier-specific.
#
# ACCEPTED FALSE POSITIVE: prettier also honors .gitignore, so a repo that
# gitignores .claude/worktrees/ is already covered and will still be warned
# here, because the prettier branch reads .prettierignore only. Consulting
# .gitignore too would silence that — but if the premise is wrong for the
# reader's prettier version, the same change silences a warning that IS due,
# and this check's whole design is that a false positive costs noise while a
# false negative costs a broken integrity pin. Noise is the side to err on.
_10e_nested=0
if [ -d "$ROOT/.claude/worktrees" ]; then
    _10e_add_kit_path ".claude/worktrees"
    # The nested checkout holds a full second copy of the pinned tree, so its
    # representative is a kit .md at nested depth — which also mirrors the
    # real matching semantics: a root-anchored "scripts/harness/**" include
    # does not reach it, a depth-agnostic "**/*.md" one does.
    _10e_add_kit_rep ".claude/worktrees/x/scripts/harness/x.md"
    _10e_nested=1
fi

# _10e_nested_note <tool-specific remedy> — the nested-checkout clause for one
# branch's warning, or nothing at all when this repo has no worktree directory.
# The REASON is shared; the REMEDY belongs to the caller, because #10e's
# governing rule (see the header above) is that no exclusion mechanism here is
# interchangeable with another: a leading '**/' is meaningful in a
# .prettierignore glob and meaningless in a pre-commit 'exclude:' regex, where
# '**' has nothing to repeat. One hardcoded prettier remedy pasted onto all
# four branches would be the exact "pointing a biome user at .prettierignore"
# error this check was written to avoid. The note also says plainly that
# .claude/worktrees/ is NOT kit-owned — it pins no file of its own and only
# appears in the missing-path list because a formatter must not descend into
# the copies it holds.
_10e_nested_note() {
    [ "$_10e_nested" = "1" ] || return 0
    # $2, when the caller has one, is that branch's missing-path list. The
    # note explains ONE path, so it must not ride along on a warning that
    # names only others -- telling a reader to exclude a directory they
    # already excluded, about an entry not in the list they were just shown,
    # is how a correct warning starts reading as boilerplate. The
    # no-.prettierignore branch passes no list because everything is missing
    # there by definition.
    if [ "$#" -ge 2 ]; then
        case "$2" in
            *".claude/worktrees"*) ;;
            *) return 0 ;;
        esac
    fi
    printf '%s' ". Note .claude/worktrees/ is not kit-owned: it holds full nested checkouts of this repo, and every exclusion mechanism here is path-anchored, so a pattern with an interior slash never matches the kit-owned copies inside one — $1"
}

_10e_kit_paths=$(printf '%s\n' "$_10e_kit_paths" | sed '/^$/d')
_10e_kit_reps=$(printf '%s\n' "$_10e_kit_reps" | sed '/^$/d')
_10e_kit_list=$(printf '%s' "$_10e_kit_paths" | tr '\n' ' ')

# _10e_reached <matcher> <entries> <kit-path> — the include-side verdict
# (issue #16): <kit-path> is reached if <matcher> reaches the directory
# itself (a dir-shaped include — the pre-#16 behavior, kept) OR any
# representative descendant file under it (an extension-shaped include the
# bare directory can never match). <matcher> is _10e_covers (dprint,
# unordered) or _10e_biome_included (biome, ordered); negations keep working
# on representatives because both matchers treat a directory entry as
# covering everything under it. A `for` over word-split lists, NOT a
# `while read`: this loop returns on the first hit, the shape
# assert_loop_ran's header says must never be fed by process substitution,
# and a `for` has no redirection to lose, so there is no silent-skip mode to
# guard against. The word-splitting (and the deliberately unquoted case
# suffix below) is safe: every representative is either a manifest path awk
# already split out of column 2 or a synthesized literal — space-free and
# glob-free by construction.
_10e_reached() {
    local _fn="$1" _entries="$2" _kp="$3" _rep
    "$_fn" "$_entries" "$_kp" && return 0
    for _rep in $_10e_kit_reps; do
        case "$_rep" in
            "$_kp"/*) "$_fn" "$_entries" "$_rep" && return 0 ;;
        esac
    done
    return 1
}

# -- prettier: .prettierignore is the exclusion mechanism (plain text, one
#    glob per line, '#' comments; no jq needed) --
# Trigger broadened beyond "a prettier config file exists": prettier runs
# perfectly well with zero config (e.g. a bare `prettier --write .` package.json
# script), which is exactly the adopter-reported case that motivated this fix —
# a config-file-only trigger silently never warned them. Fire on any of:
# a config file, "prettier" appearing anywhere in package.json (dependency,
# devDependency, or a script string — a plain grep, deliberately not a
# tokenizer), or a .prettierignore that already exists (it exists for a
# reason, and its coverage is worth checking regardless of how we found it).
_10e_prettier=0
for _10e_f in .prettierrc .prettierrc.json .prettierrc.yml .prettierrc.yaml \
              .prettierrc.json5 .prettierrc.js .prettierrc.cjs .prettierrc.mjs \
              .prettierrc.toml prettier.config.js prettier.config.cjs prettier.config.mjs; do
    [ -f "$ROOT/$_10e_f" ] && _10e_prettier=1
done
if [ -f "$ROOT/package.json" ] && grep -qE '"prettier' "$ROOT/package.json" 2>/dev/null; then
    _10e_prettier=1
fi
[ -f "$ROOT/.prettierignore" ] && _10e_prettier=1
if [ "$_10e_prettier" = "1" ]; then
    if [ ! -f "$ROOT/.prettierignore" ]; then
        echo "WARNING: prettier is configured but .prettierignore does not exist — add the harness's kit-owned paths ($_10e_kit_list) to .prettierignore, or prettier will rewrite checksum-pinned/generated files and check-harness's drift check will hard-fail$(_10e_nested_note "exclude that directory itself, or use gitignore's depth-agnostic leading '**/'")"
    else
        # Includes and negations evaluated SEPARATELY, like the biome branch
        # below: a path is covered only if some entry ignores it AND no '!'
        # entry re-includes it. _10e_covers alone strips a leading '!'
        # unconditionally, so passing raw entries straight through (the prior
        # bug) let a re-including negation (e.g. "scripts/harness/" followed
        # by "!scripts/harness/") read as coverage — the single most dangerous
        # config this check can meet, and it stayed silent.
        _10e_entries=$(grep -vE '^[[:space:]]*(#|$)' "$ROOT/.prettierignore" 2>/dev/null)
        _10e_neg=$(printf '%s\n' "$_10e_entries" | grep '^!')
        _10e_inc=$(printf '%s\n' "$_10e_entries" | grep -v '^!')
        _10e_missing=""
        _10e_read=0
        while IFS= read -r _10e_kp; do
            _10e_read=$((_10e_read + 1))
            [ -n "$_10e_kp" ] || continue
            if _10e_covers "$_10e_inc" "$_10e_kp" && ! _10e_covers "$_10e_neg" "$_10e_kp"; then
                :
            else
                _10e_missing="$_10e_missing $_10e_kp"
            fi
        done < <(printf '%s\n' "$_10e_kit_paths")
        assert_loop_ran "$_10e_read" ".prettierignore coverage check #10e"
        [ -n "$_10e_missing" ] \
            && echo "WARNING: .prettierignore does not cover kit-owned path(s):$_10e_missing — prettier will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail; add them to .prettierignore$(_10e_nested_note "exclude that directory itself, or use gitignore's depth-agnostic leading '**/'" "$_10e_missing")"
    fi
fi

# _10e_biome_included <entries, newline-separated, ORDER PRESERVED> <path> —
# biome's own documented semantics: includes/excludes are evaluated in
# order and the LAST entry matching <path> decides whether it's included,
# not "was there ever a matching negation anywhere in the list" (that
# unordered approximation is what _10e_covers's callers use for prettier/
# dprint/pre-commit, where the underlying tool has no negation ordering to
# get wrong — biome is the one format this check models with real ordering,
# and getting it wrong here is what let `["!scripts/harness/**", "**"]`
# — negation FOLLOWED by a later catch-all include that overrides it — read
# as excluded when biome would actually reformat every kit path). Returns 0
# (included -> formatter WILL touch <path>) or 1 (excluded). Starts at
# "excluded": <entries> is never truly empty by the time this is called (the
# caller substitutes a literal "**" for biome's own empty-includes-means-
# everything default), so a real, non-catch-all includes list that simply
# never mentions <path> (e.g. a repo scoped to "src/**" only) must default to
# NOT reached, not the other way around.
_10e_biome_reported=0
_10e_biome_included() {
    local _entries="$1" _path="$2" _e _neg _dd _included=0 _read=0
    while IFS= read -r _e; do
        _read=$((_read + 1))
        [ -n "$_e" ] || continue
        case "$_e" in
            '!'*) _neg=1 ;;
            *) _neg=0 ;;
        esac
        _e=${_e#\!}
        _e=${_e#./}
        _e=${_e#/}
        _e=$(printf '%s' "$_e" | tr -d "\"'")
        # Same two-sided narrowness as _10e_covers above, and it matters more
        # here: this function decides whether biome REACHES a path, so an
        # entry that wrongly stops matching produces silence, not noise.
        _dd=0
        while :; do
            case "$_e" in
                '**/'*[!*/]*) _dd=1; _e=${_e#\*\*/} ;;
                *) break ;;
            esac
        done
        _e=${_e%/\*\*}
        _e=${_e%/\*}
        _e=${_e%\*}
        _e=${_e%/}
        [ -n "$_e" ] || continue
        if [ "$_dd" = "1" ]; then
            # shellcheck disable=SC2254
            case "$_path" in
                $_e|$_e/*|*/$_e|*/$_e/*) [ "$_neg" = "1" ] && _included=0 || _included=1 ;;
            esac
        else
            # shellcheck disable=SC2254
            case "$_path" in
                $_e|$_e/*) [ "$_neg" = "1" ] && _included=0 || _included=1 ;;
            esac
        fi
    done < <(printf '%s\n' "$_entries")
    # No early exit here — biome's LAST matching entry decides, so this loop
    # must run to the end anyway, which makes it safe to convert. Its silent
    # failure would be "not included" (no warning at all), so report it — once
    # per run, not once per kit path, since one broken redirection breaks every
    # call identically and N copies would bury the finding.
    if [ "$_read" -eq 0 ] && [ "$_10e_biome_reported" -eq 0 ]; then
        _10e_biome_reported=1
        assert_loop_ran "$_read" "biome include/exclude evaluation for check #10e"
    fi
    [ "$_included" = "1" ]
}

# -- biome: files.includes / formatter.includes with ordered '!' negations --
_10e_biome_cfg=""
[ -f "$ROOT/biome.json" ] && _10e_biome_cfg="$ROOT/biome.json"
[ -f "$ROOT/biome.jsonc" ] && _10e_biome_cfg="$ROOT/biome.jsonc"
if [ -n "$_10e_biome_cfg" ]; then
    _10e_rel=${_10e_biome_cfg#"$ROOT"/}
    if ! command -v jq >/dev/null 2>&1; then
        echo "WARNING: $_10e_rel found but jq is not available — cannot verify whether kit-owned paths ($_10e_kit_list) are excluded via an ordered '!' negation in files.includes/formatter.includes; check manually"
    else
        _10e_json=$(jq -c '.' "$_10e_biome_cfg" 2>/dev/null)
        if [ -z "$_10e_json" ]; then
            echo "WARNING: $_10e_rel could not be parsed as JSON (JSONC comments/trailing commas are not valid JSON) — cannot verify kit-owned paths ($_10e_kit_list) are excluded from biome formatting; check files.includes/formatter.includes manually"
        else
            _10e_enabled=$(printf '%s' "$_10e_json" | jq -r 'if .formatter.enabled == false then "false" else "true" end' 2>/dev/null)
            if [ "$_10e_enabled" = "true" ]; then
                _10e_all=$(printf '%s' "$_10e_json" | jq -r '(.formatter.includes // .files.includes // []) | .[]?' 2>/dev/null)
                [ -z "$_10e_all" ] && _10e_all='**'
                _10e_missing=""
                _10e_read=0
                while IFS= read -r _10e_kp; do
                    _10e_read=$((_10e_read + 1))
                    [ -n "$_10e_kp" ] || continue
                    # Reached = the directory OR a representative descendant
                    # (issue #16): an extension include like "**/*.md" never
                    # matches the bare directory, and a miss on this side is
                    # silence, not noise. The warning still names the
                    # collapsed kit path — that is what the reader excludes.
                    _10e_reached _10e_biome_included "$_10e_all" "$_10e_kp" && _10e_missing="$_10e_missing $_10e_kp"
                done < <(printf '%s\n' "$_10e_kit_paths")
                assert_loop_ran "$_10e_read" "$_10e_rel formatter-coverage check #10e"
                [ -n "$_10e_missing" ] \
                    && echo "WARNING: $_10e_rel's files.includes/formatter.includes reaches kit-owned path(s):$_10e_missing without an ordered '!' negation excluding them — add e.g. \"!scripts/harness/**\" after the including entry, or biome will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail$(_10e_nested_note "add \"!.claude/worktrees/**\" after the including entry" "$_10e_missing")"
            fi
        fi
    fi
fi

# -- dprint: top-level "excludes" (a plain list, no negation ordering) --
_10e_dprint_cfg=""
[ -f "$ROOT/dprint.json" ] && _10e_dprint_cfg="$ROOT/dprint.json"
[ -f "$ROOT/dprint.jsonc" ] && _10e_dprint_cfg="$ROOT/dprint.jsonc"
if [ -n "$_10e_dprint_cfg" ]; then
    _10e_rel=${_10e_dprint_cfg#"$ROOT"/}
    if ! command -v jq >/dev/null 2>&1; then
        echo "WARNING: $_10e_rel found but jq is not available — cannot verify whether kit-owned paths ($_10e_kit_list) are listed in its \"excludes\"; check manually"
    else
        _10e_json=$(jq -c '.' "$_10e_dprint_cfg" 2>/dev/null)
        if [ -z "$_10e_json" ]; then
            echo "WARNING: $_10e_rel could not be parsed as JSON (JSONC comments/trailing commas are not valid JSON) — cannot verify kit-owned paths ($_10e_kit_list) are listed in its \"excludes\"; check manually"
        else
            _10e_inc=$(printf '%s' "$_10e_json" | jq -r '.includes // [] | .[]?' 2>/dev/null)
            _10e_exc=$(printf '%s' "$_10e_json" | jq -r '.excludes // [] | .[]?' 2>/dev/null)
            [ -z "$_10e_inc" ] && _10e_inc='**'
            _10e_missing=""
            _10e_read=0
            while IFS= read -r _10e_kp; do
                _10e_read=$((_10e_read + 1))
                [ -n "$_10e_kp" ] || continue
                # The include side asks reached-by-representative (issue
                # #16); the exclude side stays on the collapsed directory —
                # an excludes list holds prefix-style entries, and a miss
                # there fails toward noise, this check's accepted direction.
                if _10e_reached _10e_covers "$_10e_inc" "$_10e_kp"; then
                    _10e_covers "$_10e_exc" "$_10e_kp" || _10e_missing="$_10e_missing $_10e_kp"
                fi
            done < <(printf '%s\n' "$_10e_kit_paths")
            assert_loop_ran "$_10e_read" "$_10e_rel formatter-coverage check #10e"
            [ -n "$_10e_missing" ] \
                && echo "WARNING: $_10e_rel's \"includes\" reaches kit-owned path(s):$_10e_missing not listed in its \"excludes\" — add them to \"excludes\", or dprint will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail$(_10e_nested_note "add \".claude/worktrees/**\" to \"excludes\"" "$_10e_missing")"
        fi
    fi
fi

# _10e_pc_formatter_hooks <cfg-file> — one line per pre-commit hook matching
# a known formatter name: "unscoped" (no 'files:' of its own — would run
# over the whole tree), "files <pattern>" (a 'files:' key whose pattern text
# was recovered, printed for the caller to probe), or "unevaluable" (a
# 'files:' key whose value this text scan cannot recover — e.g. a block
# scalar continuing on the next line). Best-effort block scan, not a real
# YAML/indentation parser: a hook item starts at a '- id:' line; a '- repo:'
# line carries the formatter-name signal forward (a repo's own hooks can
# share a generic 'id:' with no formatter keyword in it) but is never itself
# checked for 'files:' (that field lives on the id: entry in real pre-commit
# YAML, never directly on repo:). Per-hook attribution exists so an
# UNRELATED hook's 'files:' a few lines away in the same file cannot be
# misattributed to a different, actually-unscoped formatter hook. The
# pattern is printed rather than judged here because the mere PRESENCE of a
# 'files:' key proves nothing (issue #17): 'files: \.md$' is a real scope
# that still matches every pinned/generated kit .md file pre-commit would
# pass it, so treating the key as an alibi skipped the entire coverage block
# for exactly the configs it exists to catch. The quote strip uses
# sprintf("%c", 39) for the single-quote character: a literal one inside the
# single-quoted awk program would end the shell quoting.
_10e_pc_formatter_hooks() {
    awk '
        function flush() {
            if (in_id && is_fmt) {
                if (!has_files) print "unscoped"
                else if (pat == "") print "unevaluable"
                else print "files " pat
            }
        }
        # yaml_dq_decode <double-quoted scalar body> — the regex pre-commit
        # actually receives. A YAML double-quoted scalar processes escapes
        # before the value reaches the tool, so the file text "\\.md$" IS the
        # regex \.md$ — stripping only the quotes leaves a DIFFERENT regex
        # (literal backslash, any char, md) that matches no kit file, which
        # sent this whole check silent for a hook that really does reformat
        # them. Note a single backslash before an ordinary character is not
        # valid YAML there at all, so anything this cannot decode (\n, \t,
        # \xNN, a trailing lone backslash) returns the empty string and the
        # caller reports it as unevaluable — a hedged warning, never silence.
        function yaml_dq_decode(s,   out, i, n, c, d) {
            out = ""; i = 1; n = length(s)
            while (i <= n) {
                c = substr(s, i, 1)
                if (c != "\\") { out = out c; i++; continue }
                if (i == n) return ""
                d = substr(s, i + 1, 1)
                if (d == "\\") out = out "\\"
                else if (d == "\"") out = out "\""
                else if (d == "/") out = out "/"
                else return ""
                i += 2
            }
            return out
        }
        BEGIN { repo_fmt = 0; in_id = 0; is_fmt = 0; has_files = 0; pat = "" }
        /^[[:space:]]*-[[:space:]]*repo:/ {
            flush()
            in_id = 0; is_fmt = 0; has_files = 0; pat = ""; repo_fmt = 0
            if ($0 ~ /(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)/) repo_fmt = 1
            next
        }
        /^[[:space:]]*-[[:space:]]*id:/ {
            flush()
            in_id = 1; is_fmt = repo_fmt; has_files = 0; pat = ""
            if ($0 ~ /(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)/) is_fmt = 1
            next
        }
        in_id && /^[[:space:]]*files:/ {
            has_files = 1
            line = $0
            sub(/^[[:space:]]*files:[[:space:]]*/, "", line)
            sub(/[[:space:]]+#.*$/, "", line)
            sub(/[[:space:]]+$/, "", line)
            q = substr(line, 1, 1)
            sq = sprintf("%c", 39)
            if (length(line) >= 2 && (q == "\"" || q == sq) && substr(line, length(line), 1) == q) {
                line = substr(line, 2, length(line) - 2)
                # Quoting style decides the decoding, and getting it backwards
                # in EITHER direction reintroduces the silence this check
                # exists to prevent: a double-quoted scalar processes escapes
                # (so "\\.md$" is the regex \.md$), while a single-quoted one
                # is literal apart from a doubled quote standing for one.
                if (q == "\"") line = yaml_dq_decode(line)
                else gsub(sq sq, sq, line)
            }
            pat = line
        }
        END { flush() }
    ' "$1" 2>/dev/null
}

# -- pre-commit: a top-level 'exclude:' regex, checked per kit path (fix:
#    coverage is no longer inferred from the word "harness" merely appearing
#    somewhere in the pattern — that let an exclude naming only two of five
#    required paths silently clear all five), or the formatter hook's OWN
#    'files:' — which is a scope to EVALUATE, not an alibi (issue #17): the
#    mere presence of the key used to skip this whole block, yet
#    'files: \.md$' still matches every pinned/generated kit .md file. Since
#    a 'files:' value is a Python regex largely compatible with grep -E, the
#    extracted pattern is probed against the representative kit DESCENDANT
#    files (those regexes anchor against the file paths pre-commit passes,
#    so bare directories have the same blind spot issue #16 fixed on the
#    include sides above): a match falls through to the coverage logic below
#    with hedged wording, no match is genuinely scoped (the common
#    'files: ^src/' case) and stays silent, and a pattern grep -E rejects
#    (Python-only syntax some greps cannot parse) warns hedged — per the
#    warning-only principle: when per-path coverage genuinely can't be
#    proven (no YAML parser or Python regex engine here), this WARNs with
#    hedged wording instead of silently assuming it. Hook records stay
#    block-attributed via _10e_pc_formatter_hooks, never a whole-file
#    "does any 'files:' appear anywhere" grep. --
_10e_pc_cfg=""
[ -f "$ROOT/.pre-commit-config.yaml" ] && _10e_pc_cfg="$ROOT/.pre-commit-config.yaml"
[ -f "$ROOT/.pre-commit-config.yml" ] && _10e_pc_cfg="$ROOT/.pre-commit-config.yml"
if [ -n "$_10e_pc_cfg" ]; then
    _10e_rel=${_10e_pc_cfg#"$ROOT"/}
    if grep -qE '(repo:|id:)[[:space:]]*.*(prettier|biome|dprint|black|yapf|autopep8|isort|clang-format|rustfmt|gofmt|terraform_fmt)' "$_10e_pc_cfg" 2>/dev/null; then
        _10e_pc_hooks=$(_10e_pc_formatter_hooks "$_10e_pc_cfg")
        _10e_pc_unscoped=0
        _10e_pc_kitpat=""
        _10e_pc_uneval=0
        _10e_pc_read=0
        while IFS= read -r _10e_h; do
            _10e_pc_read=$((_10e_pc_read + 1))
            [ -n "$_10e_h" ] || continue
            case "$_10e_h" in
                unscoped) _10e_pc_unscoped=1 ;;
                unevaluable) _10e_pc_uneval=1 ;;
                'files '*)
                    _10e_pat=${_10e_h#files }
                    # grep runs WITHOUT -q so it reads its whole input: -q
                    # exits on the first match, and the writer's EPIPE
                    # becomes a phantom pipefail failure under an
                    # inherited-ignored SIGPIPE (the same reason the test
                    # suite bans `printf | grep -q`). Exit 0 = the pattern
                    # reaches a representative kit file; 1 = provably
                    # scoped away from all of them; anything else = a
                    # pattern this grep cannot evaluate. Under pipefail the
                    # pipeline status is still grep's whenever grep fails,
                    # because grep is the rightmost command.
                    printf '%s\n' "$_10e_kit_reps" | grep -E -- "$_10e_pat" >/dev/null 2>&1
                    _10e_pc_rc=$?
                    if [ "$_10e_pc_rc" -eq 0 ]; then
                        _10e_pc_kitpat="$_10e_pat"
                    elif [ "$_10e_pc_rc" -ne 1 ]; then
                        _10e_pc_uneval=1
                    fi
                    ;;
            esac
        done < <(printf '%s\n' "$_10e_pc_hooks")
        assert_loop_ran "$_10e_pc_read" "$_10e_rel formatter-hook scoping scan #10e"
        [ "$_10e_pc_uneval" = "1" ] \
            && echo "WARNING: $_10e_rel has a formatter hook whose 'files:' pattern could not be evaluated as an extended regex (unsupported syntax, or a value this text scan cannot recover) — this check cannot prove the hook stays off kit-owned path(s) ($_10e_kit_list), so verify its scope manually or add a top-level 'exclude:' covering them"
        if [ "$_10e_pc_unscoped" = "1" ] || [ -n "$_10e_pc_kitpat" ]; then
            if [ "$_10e_pc_unscoped" = "1" ]; then
                _10e_pc_why="runs a formatter hook not scoped by its own 'files:'"
            else
                _10e_pc_why="runs a formatter hook whose 'files:' pattern ('$_10e_pc_kitpat') matches a representative kit file — a best-effort regex probe, not pre-commit's own matcher, so treat this as hedged"
            fi
            _10e_global_exclude=$(grep -E '^exclude:' "$_10e_pc_cfg" 2>/dev/null | head -n1)
            _10e_missing=""
            _10e_read=0
            while IFS= read -r _10e_kp; do
                _10e_read=$((_10e_read + 1))
                [ -n "$_10e_kp" ] || continue
                case "$_10e_global_exclude" in
                    *"$_10e_kp"*) ;;
                    *) _10e_missing="$_10e_missing $_10e_kp" ;;
                esac
            done < <(printf '%s\n' "$_10e_kit_paths")
            assert_loop_ran "$_10e_read" "$_10e_rel formatter-coverage check #10e"
            [ -n "$_10e_missing" ] \
                && echo "WARNING: $_10e_rel $_10e_pc_why — no real YAML parser here, so coverage can only be checked against a top-level 'exclude:', which does not demonstrably cover kit-owned path(s):$_10e_missing — pre-commit will rewrite these checksum-pinned/generated files and check-harness's drift check will hard-fail unless they are actually excluded$(_10e_nested_note "extend the exclude: regex, e.g. (^|/)[\\].claude/worktrees/ — note a glob '**/' is meaningless in a regex" "$_10e_missing")"
        fi
    fi
fi


check_trailer "doctor"
