#!/usr/bin/env bash
# Regression test for gate-command env hygiene in THIS repo's .harness/gates.conf.
#
# The defect class: several maintainer suites carry an ambient escape hatch — an
# environment variable whose mere presence makes the suite print "ok:" and exit 0
# without doing any work. They exist for good reasons (recursion breakers for
# nested fixture runs), but a gate is the TOP of a run, never a nested one. One
# variable exported in a developer's shell therefore turned six gates into
# vacuous passes: a green verify that proved nothing, with nothing in the
# transcript saying so. Measured before the fix:
# `HARNESS_NESTED_FIXTURE=1 bash scripts/test-install-recovery.sh` exits 0 in 0s;
# the same suite does 18s of real work once the gate clears the variable.
#
# The fix is `env -u VAR` in the gate command — gates.conf already used the
# sibling form `env VAR=1 ...` to PIN a knob — which makes a gate's outcome
# independent of ambient environment by construction rather than by hoping nobody
# exports it.
#
# This test stops the class from growing back. It DERIVES the hatches by scanning
# the suites rather than hard-coding them, so a hatch added to a new suite
# tomorrow fails this test until its gate clears it.
#
# NOTE ON REACH: only `gate`/`full`/`parallel` lines carry a command an `env -u`
# can live in. A `parallel-each` command is GENERATED by the runner (`bash
# <file>`), so a suite in that family cannot have a hatch cleared for it at all —
# which is why the shipped test-eval-graders.sh takes `--quick` as an argument
# rather than reading an environment variable. This test flags any parallel-each
# suite that grows an env hatch, because the only correct fix there is to stop
# reading the environment.
#
# Root-only: it reasons about this repo's tailored gate list. An adopter's
# gates.conf runs their own suites and has no counterpart.
#
# Usage: bash scripts/test-gate-env-hygiene.sh [<repo-root>]
#   The optional root is used by this file's own positive control, which builds a
#   fixture that VIOLATES the rule and asserts the scan fails it. Without that,
#   a scan that silently matched nothing would look identical to a clean repo.
set -uo pipefail

SELFTEST_ROOT="${1:-}"
ROOT="${SELFTEST_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
GATES="$ROOT/.harness/gates.conf"
[ -f "$GATES" ] || { echo "FAIL: $GATES not found"; exit 1; }
fails=0

# Variables that do not stop a suite outright but redirect it onto an input set
# whose EMPTY state is a pass ("no golden tasks under ... — checks skipped").
# Not derivable by the exit-0 scan below, so declared here with the reason.
declared_required() {
    case "$1" in
        *test-eval-graders.sh|*test-eval.sh) printf 'EVAL_TASKS_DIR\n' ;;
    esac
}

# hatch_vars <file> — names of variables guarding an early, SUCCESSFUL exit.
# Recognizes the multi-line `if [ ... ]; then ... exit 0 ... fi`, the one-line
# `[ -n "${V:-}" ] && { ...; exit 0; }`, and `case "${V:-}" in ... exit 0`.
# Scans to the closing fi/esac (bounded), not a fixed few lines: a hatch whose
# exit sits six lines below its condition is still a hatch.
hatch_vars() {
    [ -f "$1" ] || return 0
    awk '
        function trim(x) { sub(/^[[:space:]]+/, "", x); sub(/[[:space:]]+$/, "", x); return x }
        # Skip here-doc BODIES. A suite that writes a helper script with
        # `cat > shim <<SHIM ... exit 0 ... SHIM` contains an `exit 0` belonging
        # to the GENERATED file, not to its own control flow — reading it as a
        # hatch would demand an `env -u` for a variable the suite never honors.
        heredoc != "" { if (trim($0) == heredoc) heredoc = ""; next }
        match($0, /<<-?[[:space:]]*'"'"'?[A-Za-z_][A-Za-z_0-9]*'"'"'?/) {
            tag = substr($0, RSTART, RLENGTH)
            gsub(/^<<-?[[:space:]]*/, "", tag); gsub(/'"'"'/, "", tag)
            heredoc = tag; next
        }
        # A guard comparing against "$0" is a "do not run me directly"
        # self-check (install-test-lib.sh), not something an exported variable
        # can trip. BASH_* are set by the shell itself, never ambient input.
        function arm(line,    v) {
            if (line ~ /\$0/) return
            if (match(line, /\$\{[A-Z_][A-Z_0-9]*:-/) == 0) return
            v = substr(line, RSTART + 2, RLENGTH - 4)
            if (v ~ /^BASH/) return
            pend = v; n = 0
            # The one-line `&& { ...; exit 0; }` form closes immediately.
            if (line ~ /exit[[:space:]]+0/) { print pend; pend = "" }
        }
        /^[[:space:]]*(if|elif)[[:space:]]*\[/ { arm($0); next }
        /^[[:space:]]*\[[^]]*\][[:space:]]*&&/  { arm($0); next }
        /^[[:space:]]*case[[:space:]]/          { arm($0); next }
        pend != "" {
            n++
            if ($0 ~ /exit[[:space:]]+0/ || $0 ~ /^[[:space:]]*finish[[:space:]]*$/) {
                print pend; pend = ""
            } else if (n >= 40 || $0 ~ /^[[:space:]]*(fi|esac)[[:space:]]*$/) {
                pend = ""
            }
        }
    ' "$1" | sort -u
}

# script_of <gate-command> — the suite a gate runs: the token after `bash`.
script_of() {
    printf '%s\n' "$1" | awk '{ for (i = 1; i < NF; i++) if ($i == "bash") { print $(i + 1); exit } }'
}

# require_cleared <label> <rel> <cmd> <vars> — every hatch must be cleared.
require_cleared() {
    local label="$1" rel="$2" cmd="$3" vars="$4" var
    while IFS= read -r var; do
        [ -n "$var" ] || continue
        checked=$((checked + 1))
        case " $cmd " in
            *" -u $var "*) ;;
            *) echo "FAIL: gate '$label' runs $rel, which exits 0 early when \$$var is set, but the gate does not clear it."
               echo "        Add 'env -u $var' to its command in .harness/gates.conf, or the gate can pass without running."
               fails=$((fails + 1)) ;;
        esac
    done < <(printf '%s\n' "$vars")
}

gates_seen=0
checked=0
while IFS= read -r line; do
    case "$line" in ''|\#*) continue ;; esac
    kind=${line%%[[:space:]]*}
    rest=${line#"$kind"}
    rest=${rest#"${rest%%[![:space:]]*}"}
    label=${rest%%[[:space:]]*}
    cmd=${rest#"$label"}
    cmd=${cmd#"${cmd%%[![:space:]]*}"}

    case "$kind" in
        gate|full|parallel)
            gates_seen=$((gates_seen + 1))
            rel=$(script_of "$cmd")
            [ -n "$rel" ] || continue
            suite="$ROOT/$rel"
            [ -f "$suite" ] || continue
            # A suite that SOURCES install-test-lib.sh inherits its hatches.
            # Match a real source line, not any mention: test-check-harness.sh
            # names the file only in a comment.
            sources=""
            if [ "$(grep -cE '^[[:space:]]*(\.|source)[[:space:]].*install-test-lib\.sh' "$suite" 2>/dev/null)" != "0" ]; then
                sources="$ROOT/scripts/install-test-lib.sh"
            fi
            required=$( { hatch_vars "$suite"; [ -n "$sources" ] && hatch_vars "$sources"
                          declared_required "$rel"; } | sort -u)
            [ -n "$required" ] || continue
            require_cleared "$label" "$rel" "$cmd" "$required"
            ;;
        parallel-each)
            # The runner generates `bash <file>` for each match, so there is no
            # command to put an `env -u` in. A hatch here is unfixable at the
            # gate; it has to stop being an environment variable.
            for f in $cmd; do
                [ -f "$f" ] || continue
                gates_seen=$((gates_seen + 1))
                vars=$(hatch_vars "$ROOT/$f" 2>/dev/null || hatch_vars "$f")
                [ -n "$vars" ] || continue
                while IFS= read -r var; do
                    [ -n "$var" ] || continue
                    checked=$((checked + 1))
                    echo "FAIL: $f exits 0 early when \$$var is set, and it runs under the parallel-each gate '$label',"
                    echo "        whose command is generated — there is nowhere to put 'env -u $var'. Make it an"
                    echo "        argument (like test-eval-graders.sh's --quick) instead of an environment variable."
                    fails=$((fails + 1))
                done < <(printf '%s\n' "$vars")
            done
            ;;
    esac
done < "$GATES"

# Both loops must have run. Zero gates means the parse broke; zero checks means
# every hatch vanished from the scan — either way the silence above is not a pass.
if [ "$gates_seen" -eq 0 ]; then
    echo "FAIL: parsed no gate declarations from .harness/gates.conf — the scan did not run"
    fails=$((fails + 1))
elif [ "$checked" -eq 0 ]; then
    echo "FAIL: found no escape hatches to check across every gate — the derivation broke"
    fails=$((fails + 1))
fi

# Positive control: prove the FAIL branch actually fires. Skipped when we ARE the
# control (a root argument was passed), which also breaks the recursion.
if [ -z "$SELFTEST_ROOT" ]; then
    W=$(mktemp -d "${TMPDIR:-/tmp}/test-gate-env-hygiene.XXXXXX") || exit 1
    trap 'rm -rf "$W"' EXIT
    mkdir -p "$W/.harness" "$W/scripts"
    # A hatch whose exit 0 sits well below its condition — the shape a narrow
    # look-ahead window used to miss entirely.
    {
        printf '#!/usr/bin/env bash\n'
        printf 'if [ -n "${NEW_HATCH:-}" ]; then\n'
        for i in 1 2 3 4 5 6 7; do printf '    echo line%s\n' "$i"; done
        printf '    exit 0\nfi\necho real work\n'
    } > "$W/scripts/test-fixture-suite.sh"
    printf 'parallel fixture bash scripts/test-fixture-suite.sh\n' > "$W/.harness/gates.conf"
    if bash "$0" "$W" >"$W/out" 2>&1; then
        echo "FAIL: the positive control passed — an uncleared hatch was not detected, so a clean result here proves nothing"
        fails=$((fails + 1))
    else
        case "$(cat "$W/out")" in
            *NEW_HATCH*) echo "ok:   the scan fails a gate whose suite has an uncleared hatch (positive control)" ;;
            *) echo "FAIL: the positive control failed for the wrong reason:"
               sed 's/^/        /' "$W/out"; fails=$((fails + 1)) ;;
        esac
    fi
fi

if [ "$fails" -eq 0 ]; then
    echo "ok:   every gate clears the ambient escape hatches its suite honors ($checked checked across $gates_seen gates)"
    echo "PASSED: all gate-env-hygiene cases"
else
    echo "FAILED: $fails gate-env-hygiene case(s)"
    exit 1
fi
