#!/usr/bin/env bash
# test-sync-adapters.sh — `sync` (write/--check) generated
# `.harness/adapters/<slug>.md` regression coverage.
# render_adapter (sync-lib.sh) emits a blank line between the
# `<!-- generated ... -->` comment and the `# <provider>` heading; the cases
# below pin that byte and pin that `sync --check` rejects its removal. Those
# pins are cheap regression coverage, NOT proof of formatter compatibility —
# they never run an actual formatter, so they cannot detect any OTHER rewrite
# a real formatter would make (e.g. a non-default `proseWrap` reflowing the
# adapter's prose paragraph; see the accepted-gap note in render_adapter's
# comment, sync-lib.sh). The "real formatter idempotence" case further below
# closes that gap: it runs prettier, under its default config, over the
# generated adapter and asserts byte-identical output — the one assertion
# here that would survive a future prettier release changing its markdown
# printer. It is gated on prettier being available on PATH and skips cleanly
# (an `ok: ... skipped` line, not a failure) when it is not — the rest of
# this file has no such dependency, unlike `sync secrets`
# (test-sync-secrets.sh), which hard-requires jq and skips wholesale without
# it; this repo assumes bash+jq only, never npm.
set -uo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")/../.." && pwd)"   # .../scripts
SYNC="$SCRIPTS_DIR/harness/sync"

# Guarded mktemp: bare `mktemp -d` ignores $TMPDIR on macOS and fails in a
# sandbox; an empty path turns `cd ""` into a silent no-op in the HOST repo.
WORK=$(mktemp -d "${TMPDIR:-/tmp}/test-sync-adapters.XXXXXX") || exit 1
trap 'rm -rf "$WORK"' EXIT

fails=0
pass() { echo "ok:   $1"; }
fail() { echo "FAIL: $1"; fails=$((fails + 1)); }

# new_fixture <harness_providers> — a minimal tree `sync` can generate
# adapters in: the sync wrapper + the libs it sources + a harness.conf
# declaring HARNESS_PROVIDERS. No skill/agent/hook config trees are needed —
# every canonical-source glob in sync-lib.sh is guarded with
# `[ -f ... ] || continue`, so the adapter-generation tail runs standalone.
new_fixture() {
    local w hp="$1"
    w=$(mktemp -d "$WORK/fx.XXXXXX") || return 1
    mkdir -p "$w/scripts/harness/lib"
    cp "$SYNC" "$w/scripts/harness/sync"
    cp "$SCRIPTS_DIR/harness/lib/sync-lib.sh" "$w/scripts/harness/lib/"
    cp "$SCRIPTS_DIR/harness/lib/provider-lib.sh" "$w/scripts/harness/lib/"
    cp "$SCRIPTS_DIR/harness/lib/provider-caps" "$w/scripts/harness/lib/"
    chmod +x "$w/scripts/harness/sync"
    printf 'HARNESS_PROVIDERS="%s"\n' "$hp" > "$w/scripts/harness/harness.conf"
    printf '%s' "$w"
}

# --- write generates a formatter-clean adapter -------------------------------
W=$(new_fixture ".claude")
ADAPTER="$W/.harness/adapters/claude.md"

out=$(bash "$W/scripts/harness/sync" 2>&1); rc=$?
if [ "$rc" -eq 0 ]; then
    pass "sync (write) generates adapters"
else
    fail "sync (write) generates adapters"
    printf '%s\n' "$out" | sed 's/^/        /'
fi

if [ -f "$ADAPTER" ]; then
    pass ".harness/adapters/claude.md was written"
else
    fail ".harness/adapters/claude.md was written"
fi

# The formatter-compat fix: a blank line MUST separate the generated-by
# comment (line 1) from the `# provider — harness wiring adapter` heading
# (line 3) — line 2 must be empty. Without it, a markdown formatter that
# inserts that blank line would immediately re-drift `sync --check`.
line1=$(sed -n '1p' "$ADAPTER" 2>/dev/null)
line2=$(sed -n '2p' "$ADAPTER" 2>/dev/null)
line3=$(sed -n '3p' "$ADAPTER" 2>/dev/null)
case "$line1" in
    "<!-- generated by scripts/harness/sync"*) pass "line 1 is the generated-by comment" ;;
    *) fail "line 1 is the generated-by comment (got: '$line1')" ;;
esac
if [ -z "$line2" ]; then
    pass "blank line separates the generated-by comment from the heading"
else
    fail "blank line separates the generated-by comment from the heading (got: '$line2')"
fi
case "$line3" in
    "# .claude — harness wiring adapter") pass "heading follows the blank line" ;;
    *) fail "heading follows the blank line (got: '$line3')" ;;
esac

# --- real formatter idempotence: prettier's DEFAULT config only -------------
# The line-by-line pins above assert the exact bytes the generator currently
# emits; they cannot catch a rewrite from an actual formatter run (e.g. a
# non-default `proseWrap` reflowing the prose paragraph below the heading —
# an accepted, documented gap, not something this case is meant to close).
# This is the one assertion that runs a real formatter: pipe the generated
# adapter through prettier with no config (its shipped defaults) and require
# byte-identical output. The comparison is file-level (`cmp`), not a shell
# command-substitution string compare — command substitution strips ALL
# trailing newlines from both sides, which would hide the likeliest formatter
# delta (a final-newline add/remove/normalize) despite that being exactly the
# kind of drift this case exists to catch. Gated on prettier being on PATH;
# skips cleanly, the same way test-sync-secrets.sh skips without jq, rather
# than failing when it is absent — this repo assumes bash+jq only, never npm,
# as a hard test dependency.
if command -v prettier >/dev/null 2>&1; then
    if prettier "$ADAPTER" > "$ADAPTER.prettier" 2>/dev/null && cmp -s "$ADAPTER.prettier" "$ADAPTER"; then
        pass "prettier (default config) reproduces the generated adapter byte-for-byte"
    else
        fail "prettier (default config) reproduces the generated adapter byte-for-byte"
    fi
else
    pass "prettier idempotence check skipped (prettier unavailable on PATH)"
fi

# --- sync --check is clean immediately after write ---------------------------
if bash "$W/scripts/harness/sync" --check >/dev/null 2>&1; then
    pass "sync --check is clean after a fresh write"
else
    fail "sync --check is clean after a fresh write"
fi

# --- the deadlock scenario: stripping the blank line re-drifts --check -------
# Simulates the byte-exact regression this fix prevents (a formatter, or a
# hand-edit, dropping the blank line) — --check must catch it, proving the
# blank line is actually enforced and not just emitted once by `sync` itself.
# Every setup step below is gated behind setup_ok: fail() increments a counter
# but does not exit, so an ungated setup failure could let the final --check
# exit nonzero for the WRONG reason (a broken fixture, not the mutation) and
# still read as a pass. setup_ok=0 routes straight to an explicit fail instead
# of falling through to the real assertion.
setup_ok=1
W2=$(new_fixture ".claude")
if [ -z "$W2" ]; then
    fail "deadlock scenario setup: fixture"
    setup_ok=0
fi

if [ "$setup_ok" -eq 1 ]; then
    ADAPTER2="$W2/.harness/adapters/claude.md"
    if ! bash "$W2/scripts/harness/sync" >/dev/null 2>&1; then
        fail "deadlock scenario setup: initial sync (write)"
        setup_ok=0
    fi
fi

# Prove the baseline is clean BEFORE the mutation, so a later nonzero --check
# exit is attributable to the mutation and not to some other setup defect.
if [ "$setup_ok" -eq 1 ] && ! bash "$W2/scripts/harness/sync" --check >/dev/null 2>&1; then
    fail "deadlock scenario setup: --check is clean before the mutation"
    setup_ok=0
fi

if [ "$setup_ok" -eq 1 ]; then
    if ! { awk 'NR==2 && $0=="" { next } { print }' "$ADAPTER2" > "$ADAPTER2.stripped" \
        && mv "$ADAPTER2.stripped" "$ADAPTER2"; }; then
        fail "deadlock scenario setup: blank-line-stripping mutation"
        setup_ok=0
    fi
fi

# Confirm the mutation actually landed: in a healthy adapter line 2 is blank
# (per the pins above); after stripping it, the old line 3 heading moves up,
# so line 2 must now be non-blank.
if [ "$setup_ok" -eq 1 ]; then
    line2_mutated=$(sed -n '2p' "$ADAPTER2" 2>/dev/null)
    if [ -z "$line2_mutated" ]; then
        fail "deadlock scenario setup: blank line was not actually removed"
        setup_ok=0
    fi
fi

if [ "$setup_ok" -eq 1 ]; then
    if bash "$W2/scripts/harness/sync" --check >/dev/null 2>&1; then
        fail "sync --check re-flags an adapter with the blank line stripped"
    else
        pass "sync --check re-flags an adapter with the blank line stripped"
    fi
else
    fail "sync --check re-flags an adapter with the blank line stripped (not exercised — setup failed above)"
fi

if [ "$fails" -eq 0 ]; then
    echo "PASSED: sync adapter formatter-compat"
    exit 0
fi
echo "FAILED: $fails sync-adapters case(s)"
exit 1
